# Terminal, Screenshots & Program Launcher (Rofi){{{
# start a terminal
bindsym $mod+Return exec kitty

# A more modern dmenu replacement is rofi:
bindsym $mod+d exec "rofi -modi drun,run -show drun -font 'Hack Nerd Font' -icon-theme 'candy-icons' -show-icons"
# Calculator with Rofi
bindsym $mod+c exec rofi -show calc -modi calc -no-show-match -no-sort

# Screenshots
bindsym $mod+x exec scrot

#}}}

# Kill, Focus, Move windows {{{
# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+ntilde focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+ntilde move right

#}}}

# Split orientation and focus between windows {{{
# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# Switch between horizontal and vertical split
bindsym $mod+t split toggle

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent
#}}}

# Layouts{{{
# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
#}}}

# Reload, Lock, Restart & Exit i3 {{{
# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
# Lock I3 
bindsym $mod+mod1+l exec dm-tool lock
#}}}

