# Styles of Windows {{{
# Borders of the windows
for_window [class="^.*"] border pixel 4

# Windows title alignment
title_align center

# i3 colors
# Windows colors
# Class			border  backgr.  text   indicator  child_border
client.focused 		#8DC5DA #4E6E8B #131820 #A0BA7C #4E6E8B
client.focused_inactive #4F79B9 #324957 #6D9E7A #657652 #4E6E8B
client.unfocused 	#1E2A2D #324957 #A0BA7C #9EC1B0 #4F79B9
client.urgent 		#8DC5DA #9EC1B0 #253959 #B7D8E1 #67A4B1
client.placeholder 	#000000 #2D3B4C #9EC1B0 #000000 #67A4B1
client.background 	#4E6E8B

# Delaying urgency hint reset on workspace change
force_display_urgency_hint 500 ms

# Spaces between windows
gaps outer 15
gaps inner 10
smart_gaps on
#}}}
