#!/bin/sh

# Start some apps
~/.config/bspwm/autostart.sh

# Initialize sxhkd for keymaps
pgrep -x sxhkd > /dev/null || sxhkd &

# Set desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Border and gaps of the windows
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules for windoows
bspc rule -a mGBA state=floating
bspc rule -a Citra state=floating
bspc rule -a PPSSPPQt state=floating
bspc rule -a m64py state=floating
bspc rule -a dolphin-emu state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Snes9x-gtk state=floating
bspc rule -a gnome-calculator state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Gimp state=floating

# Set rules for type and role windows
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"
