#! /bin/sh

# This function only executes a program if it's not already running
run() {
  if ! pgrep -f "$1"; then
    "$@" &
  fi
}

# Set keyboard layout to es-latam
setxkbmap latam

# Start picom (transparency and animations for windows)
run picom -b

# Start the notification daemon
run dunst

# Start mpd
run mpd ~/.config/mpd/mpd.conf

# Start script to check battery charge.
run ~/.scripts/battery_check.sh

# Initialize sxhkd for keymaps
pgrep -x sxhkd > /dev/null || sxhkd &

# Set the wallpapper for bspwm
xwallpaper --zoom ~/Images/Wallpapers/wallhaven-j5l2wm.png

# Set desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# Border and gaps of the windows
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules for windoows
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
