#!/bin/sh

# Start some apps
~/.config/bspwm/autostart.sh

# Initialize sxhkd for keymaps
pgrep -x sxhkd > /dev/null || sxhkd &

# Set desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Border and gaps of the windows
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules for windoows
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
