[general]
import = [
    "~/.config/alacritty/colors.toml"
]
live_config_reload = true

[window]
decorations = "None"
dynamic_title = true

[font]
normal = {family = "Terminess Nerd Font", style = "Regular"}
bold = {family = "Terminess Nerd Font", style = "Bold"}
italic = {family = "Terminess Nerd Font", style = "Italic"}
bold_italic = {family = "Terminess Nerd Font", style = "Bold Italic"}
size = 9.5

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Underline", blinking = "Always"}
vi_mode_style = {shape = "Block", blinking = "On"}
blink_timeout = 0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"}
]

