
[window]
decorations = "None"
dynamic_title = true

[font]
size = 10.0
normal = {family = "Terminess Nerd Font", style = "Regular"}
bold = {family = "Terminess Nerd Font", style = "Bold"}
italic = {family = "Terminess Nerd Font", style = "Italic"}
bold_italic = {family = "Terminess Nerd Font", style = "Bold Italic"}

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Underline", blinking = "Always"}
vi_mode_style = {shape = "Block", blinking = "On"}

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"}
]

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/dark_pride.toml"
]
