# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
# END WAL
# BEGIN WAL
[colors.primary]
background = '#00000D'
foreground = '#91e1d1'

[colors.cursor]
text   = '#00000D'
cursor = '#91e1d1'

[colors.vi_mode_cursor]
text   = '#00000D'
cursor = '#91e1d1'

[colors.search.matches]
foreground = '#00000D'
background = '#91e1d1'

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#659d92'
background = '#91e1d1'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#00000D'
red     = '#AB345F'
green   = '#F35D70'
yellow  = '#3EBC75'
blue    = '#F2B670'
magenta = '#215C93'
cyan    = '#E8678D'
white   = '#91e1d1'

[colors.bright]
black   = '#659d92'
red     = '#AB345F'
green   = '#F35D70'
yellow  = '#3EBC75'
blue    = '#F2B670'
magenta = '#215C93'
cyan    = '#E8678D'
white   = '#91e1d1'
# END WAL
